using AzRanger.Output;
using System;

namespace AzRanger.Models.ExchangeOnline
{
    public class Mailbox : IReporting
    {
        public string Database { get; set; }
        public string DatabaseGuiddatatype { get; set; }
        public string DatabaseGuidodatatype { get; set; }
        public string DatabaseGuid { get; set; }
        public object MailboxProvisioningConstraint { get; set; }
        public bool IsMonitoringMailbox { get; set; }
        public object MailboxRegion { get; set; }
        public object MailboxRegionLastUpdateTime { get; set; }
        public string MailboxRegionSuffix { get; set; }
        public bool MessageRecallProcessingEnabled { get; set; }
        public bool MessageCopyForSentAsEnabled { get; set; }
        public bool MessageCopyForSendOnBehalfEnabled { get; set; }
        public string MailboxProvisioningPreferencesodatatype { get; set; }
        public object[] MailboxProvisioningPreferences { get; set; }
        public bool UseDatabaseRetentionDefaults { get; set; }
        public bool RetainDeletedItemsUntilBackup { get; set; }
        public bool DeliverToMailboxAndForward { get; set; }
        public bool IsExcludedFromServingHierarchy { get; set; }
        public bool IsHierarchyReady { get; set; }
        public bool IsHierarchySyncEnabled { get; set; }
        public bool HasSnackyAppData { get; set; }
        public bool LitigationHoldEnabled { get; set; }
        public bool SingleItemRecoveryEnabled { get; set; }
        public bool RetentionHoldEnabled { get; set; }
        public object EndDateForRetentionHold { get; set; }
        public object StartDateForRetentionHold { get; set; }
        public string RetentionComment { get; set; }
        public string RetentionUrl { get; set; }
        public object LitigationHoldDate { get; set; }
        public string LitigationHoldOwner { get; set; }
        public bool ElcProcessingDisabled { get; set; }
        public bool ComplianceTagHoldApplied { get; set; }
        public bool WasInactiveMailbox { get; set; }
        public bool DelayHoldApplied { get; set; }
        public bool DelayReleaseHoldApplied { get; set; }
        public object InactiveMailboxRetireTime { get; set; }
        public object OrphanSoftDeleteTrackingTime { get; set; }
        public string LitigationHoldDuration { get; set; }
        public object ManagedFolderMailboxPolicy { get; set; }
        public string RetentionPolicy { get; set; }
        public object AddressBookPolicy { get; set; }
        public bool CalendarRepairDisabled { get; set; }
        public string ExchangeGuiddatatype { get; set; }
        public string ExchangeGuidodatatype { get; set; }
        public string ExchangeGuid { get; set; }
        public object MailboxContainerGuid { get; set; }
        public object UnifiedMailbox { get; set; }
        public string MailboxLocationsodatatype { get; set; }
        public string[] MailboxLocations { get; set; }
        public string AggregatedMailboxGuidsodatatype { get; set; }
        public object[] AggregatedMailboxGuids { get; set; }
        public string ExchangeSecurityDescriptor { get; set; }
        public string ExchangeUserAccountControl { get; set; }
        public string AdminDisplayVersion { get; set; }
        public bool MessageTrackingReadStatusEnabled { get; set; }
        public string ExternalOofOptions { get; set; }
        public object ForwardingAddress { get; set; }
        public object ForwardingSmtpAddress { get; set; }
        public string RetainDeletedItemsFor { get; set; }
        public bool IsMailboxEnabled { get; set; }
        public string Languagesodatatype { get; set; }
        public object[] Languages { get; set; }
        public object OfflineAddressBook { get; set; }
        public string ProhibitSendQuota { get; set; }
        public string ProhibitSendReceiveQuota { get; set; }
        public string RecoverableItemsQuota { get; set; }
        public string RecoverableItemsWarningQuota { get; set; }
        public string CalendarLoggingQuota { get; set; }
        public bool DowngradeHighPriorityMessagesEnabled { get; set; }
        public string ProtocolSettingsodatatype { get; set; }
        public string[] ProtocolSettings { get; set; }
        public string RecipientLimits { get; set; }
        public bool ImListMigrationCompleted { get; set; }
        public object SiloName { get; set; }
        public bool IsResource { get; set; }
        public bool IsLinked { get; set; }
        public bool IsShared { get; set; }
        public bool IsRootPublicFolderMailbox { get; set; }
        public string LinkedMasterAccount { get; set; }
        public bool ResetPasswordOnNextLogon { get; set; }
        public object ResourceCapacity { get; set; }
        public string ResourceCustomodatatype { get; set; }
        public object[] ResourceCustom { get; set; }
        public object ResourceType { get; set; }
        public object RoomMailboxAccountEnabled { get; set; }
        public string SamAccountName { get; set; }
        public object SCLDeleteThreshold { get; set; }
        public object SCLDeleteEnabled { get; set; }
        public object SCLRejectThreshold { get; set; }
        public object SCLRejectEnabled { get; set; }
        public object SCLQuarantineThreshold { get; set; }
        public object SCLQuarantineEnabled { get; set; }
        public object SCLJunkThreshold { get; set; }
        public object SCLJunkEnabled { get; set; }
        public bool AntispamBypassEnabled { get; set; }
        public string ServerLegacyDN { get; set; }
        public string ServerName { get; set; }
        public bool UseDatabaseQuotaDefaults { get; set; }
        public string IssueWarningQuota { get; set; }
        public string RulesQuota { get; set; }
        public string Office { get; set; }
        public string UserPrincipalName { get; set; }
        public bool UMEnabled { get; set; }
        public object MaxSafeSenders { get; set; }
        public object MaxBlockedSenders { get; set; }
        public string NetID { get; set; }
        public object ReconciliationId { get; set; }
        public string WindowsLiveID { get; set; }
        public string MicrosoftOnlineServicesID { get; set; }
        public object ThrottlingPolicy { get; set; }
        public string RoleAssignmentPolicy { get; set; }
        public object DefaultPublicFolderMailbox { get; set; }
        public object EffectivePublicFolderMailbox { get; set; }
        public string SharingPolicy { get; set; }
        public object RemoteAccountPolicy { get; set; }
        public string MailboxPlan { get; set; }
        public object ArchiveDatabase { get; set; }
        public string ArchiveDatabaseGuiddatatype { get; set; }
        public string ArchiveDatabaseGuidodatatype { get; set; }
        public string ArchiveDatabaseGuid { get; set; }
        public string ArchiveGuiddatatype { get; set; }
        public string ArchiveGuidodatatype { get; set; }
        public string ArchiveGuid { get; set; }
        public string ArchiveNameodatatype { get; set; }
        public object[] ArchiveName { get; set; }
        public string JournalArchiveAddress { get; set; }
        public string ArchiveQuota { get; set; }
        public string ArchiveWarningQuota { get; set; }
        public object ArchiveDomain { get; set; }
        public string ArchiveStatus { get; set; }
        public string ArchiveState { get; set; }
        public bool AutoExpandingArchiveEnabled { get; set; }
        public bool DisabledMailboxLocations { get; set; }
        public string RemoteRecipientType { get; set; }
        public object DisabledArchiveDatabase { get; set; }
        public string DisabledArchiveGuiddatatype { get; set; }
        public string DisabledArchiveGuidodatatype { get; set; }
        public string DisabledArchiveGuid { get; set; }
        public object QueryBaseDN { get; set; }
        public bool QueryBaseDNRestrictionEnabled { get; set; }
        public object MailboxMoveTargetMDB { get; set; }
        public object MailboxMoveSourceMDB { get; set; }
        public string MailboxMoveFlags { get; set; }
        public string MailboxMoveRemoteHostName { get; set; }
        public string MailboxMoveBatchName { get; set; }
        public string MailboxMoveStatus { get; set; }
        public string MailboxRelease { get; set; }
        public string ArchiveRelease { get; set; }
        public bool IsPersonToPersonTextMessagingEnabled { get; set; }
        public bool IsMachineToPersonTextMessagingEnabled { get; set; }
        public string UserSMimeCertificateodatatype { get; set; }
        public object[] UserSMimeCertificate { get; set; }
        public string UserCertificateodatatype { get; set; }
        public object[] UserCertificate { get; set; }
        public bool CalendarVersionStoreDisabled { get; set; }
        public string ImmutableId { get; set; }
        public string PersistedCapabilitiesodatatype { get; set; }
        public string[] PersistedCapabilities { get; set; }
        public object SKUAssigned { get; set; }
        public bool AuditEnabled { get; set; }
        public string AuditLogAgeLimit { get; set; }
        public string AuditAdminodatatype { get; set; }
        public string[] AuditAdmin { get; set; }
        public string AuditDelegateodatatype { get; set; }
        public string[] AuditDelegate { get; set; }
        public string AuditOwnerodatatype { get; set; }
        public string[] AuditOwner { get; set; }
        public string DefaultAuditSetodatatype { get; set; }
        public string[] DefaultAuditSet { get; set; }
        public string WhenMailboxCreateddatatype { get; set; }
        public DateTime WhenMailboxCreated { get; set; }
        public string SourceAnchor { get; set; }
        public string UsageLocation { get; set; }
        public bool IsSoftDeletedByRemove { get; set; }
        public bool IsSoftDeletedByDisable { get; set; }
        public bool IsInactiveMailbox { get; set; }
        public bool IncludeInGarbageCollection { get; set; }
        public object WhenSoftDeleted { get; set; }
        public string InPlaceHoldsodatatype { get; set; }
        public object[] InPlaceHolds { get; set; }
        public string GeneratedOfflineAddressBooksodatatype { get; set; }
        public object[] GeneratedOfflineAddressBooks { get; set; }
        public bool AccountDisabled { get; set; }
        public object StsRefreshTokensValidFromdatatype { get; set; }
        public object StsRefreshTokensValidFrom { get; set; }
        public string NonCompliantDevicesodatatype { get; set; }
        public object[] NonCompliantDevices { get; set; }
        public string EnforcedTimestamps { get; set; }
        public object DataEncryptionPolicy { get; set; }
        public bool MessageCopyForSMTPClientSubmissionEnabled { get; set; }
        public string RecipientThrottlingThreshold { get; set; }
        public string SharedEmailDomainTenant { get; set; }
        public string SharedEmailDomainState { get; set; }
        public string SharedWithTargetSmtpAddress { get; set; }
        public object SharedEmailDomainStateLastModified { get; set; }
        public string Extensionsodatatype { get; set; }
        public object[] Extensions { get; set; }
        public bool HasPicture { get; set; }
        public bool HasSpokenName { get; set; }
        public bool IsDirSynced { get; set; }
        public string AcceptMessagesOnlyFromodatatype { get; set; }
        public object[] AcceptMessagesOnlyFrom { get; set; }
        public string AcceptMessagesOnlyFromDLMembersodatatype { get; set; }
        public object[] AcceptMessagesOnlyFromDLMembers { get; set; }
        public string AcceptMessagesOnlyFromSendersOrMembersodatatype { get; set; }
        public object[] AcceptMessagesOnlyFromSendersOrMembers { get; set; }
        public string AddressListMembershipodatatype { get; set; }
        public string[] AddressListMembership { get; set; }
        public string AdministrativeUnitsodatatype { get; set; }
        public object[] AdministrativeUnits { get; set; }
        public string Alias { get; set; }
        public object ArbitrationMailbox { get; set; }
        public string BypassModerationFromSendersOrMembersodatatype { get; set; }
        public object[] BypassModerationFromSendersOrMembers { get; set; }
        public string OrganizationalUnit { get; set; }
        public string CustomAttribute1 { get; set; }
        public string CustomAttribute10 { get; set; }
        public string CustomAttribute11 { get; set; }
        public string CustomAttribute12 { get; set; }
        public string CustomAttribute13 { get; set; }
        public string CustomAttribute14 { get; set; }
        public string CustomAttribute15 { get; set; }
        public string CustomAttribute2 { get; set; }
        public string CustomAttribute3 { get; set; }
        public string CustomAttribute4 { get; set; }
        public string CustomAttribute5 { get; set; }
        public string CustomAttribute6 { get; set; }
        public string CustomAttribute7 { get; set; }
        public string CustomAttribute8 { get; set; }
        public string CustomAttribute9 { get; set; }
        public string ExtensionCustomAttribute1odatatype { get; set; }
        public object[] ExtensionCustomAttribute1 { get; set; }
        public string ExtensionCustomAttribute2odatatype { get; set; }
        public object[] ExtensionCustomAttribute2 { get; set; }
        public string ExtensionCustomAttribute3odatatype { get; set; }
        public object[] ExtensionCustomAttribute3 { get; set; }
        public string ExtensionCustomAttribute4odatatype { get; set; }
        public object[] ExtensionCustomAttribute4 { get; set; }
        public string ExtensionCustomAttribute5odatatype { get; set; }
        public object[] ExtensionCustomAttribute5 { get; set; }
        public string DisplayName { get; set; }
        public string EmailAddressesodatatype { get; set; }
        public string[] EmailAddresses { get; set; }
        public string GrantSendOnBehalfToodatatype { get; set; }
        public object[] GrantSendOnBehalfTo { get; set; }
        public string ExternalDirectoryObjectId { get; set; }
        public bool HiddenFromAddressListsEnabled { get; set; }
        public object LastExchangeChangedTime { get; set; }
        public string LegacyExchangeDN { get; set; }
        public string MaxSendSize { get; set; }
        public string MaxReceiveSize { get; set; }
        public string ModeratedByodatatype { get; set; }
        public object[] ModeratedBy { get; set; }
        public bool ModerationEnabled { get; set; }
        public string PoliciesIncludedodatatype { get; set; }
        public object[] PoliciesIncluded { get; set; }
        public string PoliciesExcludedodatatype { get; set; }
        public string[] PoliciesExcluded { get; set; }
        public bool EmailAddressPolicyEnabled { get; set; }
        public string PrimarySmtpAddress { get; set; }
        public string RecipientType { get; set; }
        public string RecipientTypeDetails { get; set; }
        public string RejectMessagesFromodatatype { get; set; }
        public object[] RejectMessagesFrom { get; set; }
        public string RejectMessagesFromDLMembersodatatype { get; set; }
        public object[] RejectMessagesFromDLMembers { get; set; }
        public string RejectMessagesFromSendersOrMembersodatatype { get; set; }
        public object[] RejectMessagesFromSendersOrMembers { get; set; }
        public bool RequireSenderAuthenticationEnabled { get; set; }
        public string SimpleDisplayName { get; set; }
        public string SendModerationNotifications { get; set; }
        public string UMDtmfMapodatatype { get; set; }
        public string[] UMDtmfMap { get; set; }
        public string WindowsEmailAddress { get; set; }
        public object MailTip { get; set; }
        public string MailTipTranslationsodatatype { get; set; }
        public object[] MailTipTranslations { get; set; }
        public string Identity { get; set; }
        public string Id { get; set; }
        public bool IsValid { get; set; }
        public object Item { get; set; }
        public string ExchangeVersion { get; set; }
        public string Name { get; set; }
        public string DistinguishedName { get; set; }
        public string ObjectCategory { get; set; }
        public string ObjectClassodatatype { get; set; }
        public string[] ObjectClass { get; set; }
        public string WhenChangeddatatype { get; set; }
        public DateTime WhenChanged { get; set; }
        public string WhenCreateddatatype { get; set; }
        public DateTime WhenCreated { get; set; }
        public string WhenChangedUTCdatatype { get; set; }
        public DateTime WhenChangedUTC { get; set; }
        public string WhenCreatedUTCdatatype { get; set; }
        public DateTime WhenCreatedUTC { get; set; }
        public string ExchangeObjectIddatatype { get; set; }
        public string ExchangeObjectIdodatatype { get; set; }
        public string ExchangeObjectId { get; set; }
        public string OrganizationalUnitRoot { get; set; }
        public string OrganizationId { get; set; }
        public string Guiddatatype { get; set; }
        public string Guidodatatype { get; set; }
        public string Guid { get; set; }
        public string OriginatingServer { get; set; }

        public string PrintConsole()
        {
            return String.Format("{0} - {1}", this.UserPrincipalName, this.Id);
        }

        public string PrintCSV()
        {
            return String.Format("{0};{1}", this.Id, this.UserPrincipalName);
        }
        public AffectedItem GetAffectedItem()
        {
            return new AffectedItem(this.Id, this.UserPrincipalName);
        }
    }

}
