using System;

namespace AzRanger.Models.ExchangeOnline
{
    public class OrganizationConfig
    {
        public string OrganizationId { get; set; }
        public string Name { get; set; }
        public string Identity { get; set; }
        public string Guiddatatype { get; set; }
        public string Guidodatatype { get; set; }
        public string Guid { get; set; }
        public string ObjectVersiondatatype { get; set; }
        public int ObjectVersion { get; set; }
        public object DefaultPublicFolderAgeLimit { get; set; }
        public string DefaultPublicFolderIssueWarningQuota { get; set; }
        public string DefaultPublicFolderProhibitPostQuota { get; set; }
        public string DefaultPublicFolderMaxItemSize { get; set; }
        public string DefaultPublicFolderDeletedItemRetention { get; set; }
        public string DefaultPublicFolderMovedItemRetention { get; set; }
        public bool PublicFoldersLockedForMigration { get; set; }
        public bool PublicFolderMigrationComplete { get; set; }
        public bool PublicFolderMailboxesLockedForNewConnections { get; set; }
        public bool PublicFolderMailboxesMigrationComplete { get; set; }
        public bool PublicFolderShowClientControl { get; set; }
        public string PublicFoldersEnabled { get; set; }
        public bool ActivityBasedAuthenticationTimeoutEnabled { get; set; }
        public string ActivityBasedAuthenticationTimeoutInterval { get; set; }
        public bool ActivityBasedAuthenticationTimeoutWithSingleSignOnEnabled { get; set; }
        public bool AppsForOfficeEnabled { get; set; }
        public string AppsForOfficeCorpCatalogAppsCountdatatype { get; set; }
        public int AppsForOfficeCorpCatalogAppsCount { get; set; }
        public string PrivateCatalogAppsCountdatatype { get; set; }
        public int PrivateCatalogAppsCount { get; set; }
        public object AVAuthenticationService { get; set; }
        public object CustomerFeedbackEnabled { get; set; }
        public object DistributionGroupDefaultOU { get; set; }
        public string DistributionGroupNameBlockedWordsListodatatype { get; set; }
        public object[] DistributionGroupNameBlockedWordsList { get; set; }
        public string DistributionGroupNamingPolicy { get; set; }
        public object EwsAllowEntourage { get; set; }
        public object EwsAllowList { get; set; }
        public object EwsAllowMacOutlook { get; set; }
        public object EwsAllowOutlook { get; set; }
        public bool AllowPlusAddressInRecipients { get; set; }
        public bool MaskClientIpInReceivedHeadersEnabled { get; set; }
        public object EwsApplicationAccessPolicy { get; set; }
        public object EwsBlockList { get; set; }
        public bool AutodiscoverPartialDirSync { get; set; }
        public object EwsEnabled { get; set; }
        public string IPListBlockedodatatype { get; set; }
        public object[] IPListBlocked { get; set; }
        public bool ElcProcessingDisabled { get; set; }
        public bool AutoExpandingArchiveEnabled { get; set; }
        public bool ComplianceMLBgdCrawlEnabled { get; set; }
        public bool ExchangeNotificationEnabled { get; set; }
        public string ExchangeNotificationRecipientsodatatype { get; set; }
        public object[] ExchangeNotificationRecipients { get; set; }
        public object HierarchicalAddressBookRoot { get; set; }
        public string Industry { get; set; }
        public bool MailTipsAllTipsEnabled { get; set; }
        public bool MailTipsExternalRecipientsTipsEnabled { get; set; }
        public bool MailTipsGroupMetricsEnabled { get; set; }
        public string MailTipsLargeAudienceThresholddatatype { get; set; }
        public string MailTipsLargeAudienceThresholdodatatype { get; set; }
        public int MailTipsLargeAudienceThreshold { get; set; }
        public bool MailTipsMailboxSourcedTipsEnabled { get; set; }
        public string ManagedFolderHomepage { get; set; }
        public string MicrosoftExchangeRecipientEmailAddressesodatatype { get; set; }
        public string[] MicrosoftExchangeRecipientEmailAddresses { get; set; }
        public bool MicrosoftExchangeRecipientEmailAddressPolicyEnabled { get; set; }
        public string MicrosoftExchangeRecipientPrimarySmtpAddress { get; set; }
        public object MicrosoftExchangeRecipientReplyRecipient { get; set; }
        public bool ForwardSyncLiveIdBusinessInstance { get; set; }
        public string OrganizationSummaryodatatype { get; set; }
        public object[] OrganizationSummary { get; set; }
        public bool ReadTrackingEnabled { get; set; }
        public string SCLJunkThresholddatatype { get; set; }
        public int SCLJunkThreshold { get; set; }
        public object SIPAccessService { get; set; }
        public object SIPSessionBorderController { get; set; }
        public string MaxConcurrentMigrations { get; set; }
        public object MaxAddressBookPolicies { get; set; }
        public object MaxOfflineAddressBooks { get; set; }
        public object MaxInformationBarrierSegments { get; set; }
        public string MaxIBSegmentsdatatype { get; set; }
        public int MaxIBSegments { get; set; }
        public string MaxIBBridgesdatatype { get; set; }
        public int MaxIBBridges { get; set; }
        public bool IsExcludedFromOnboardMigration { get; set; }
        public bool IsExcludedFromOffboardMigration { get; set; }
        public bool IsFfoMigrationInProgress { get; set; }
        public bool ExternalCloudAccessEnabled { get; set; }
        public bool IsProcessEhaMigratedMessagesEnabled { get; set; }
        public bool TenantRelocationsAllowed { get; set; }
        public bool ACLableSyncedObjectEnabled { get; set; }
        public string PreferredInternetCodePageForShiftJisdatatype { get; set; }
        public int PreferredInternetCodePageForShiftJis { get; set; }
        public string RequiredCharsetCoveragedatatype { get; set; }
        public int RequiredCharsetCoverage { get; set; }
        public string ByteEncoderTypeFor7BitCharsetsdatatype { get; set; }
        public int ByteEncoderTypeFor7BitCharsets { get; set; }
        public bool PublicComputersDetectionEnabled { get; set; }
        public string RmsoSubscriptionStatus { get; set; }
        public bool IntuneManagedStatus { get; set; }
        public bool AzurePremiumSubscriptionStatus { get; set; }
        public string HybridConfigurationStatus { get; set; }
        public object ReleaseTrack { get; set; }
        public object CompassEnabled { get; set; }
        public string SharePointUrl { get; set; }
        public bool MapiHttpEnabled { get; set; }
        public bool RealTimeLogServiceEnabled { get; set; }
        public bool CustomerLockboxEnabled { get; set; }
        public bool OAuth2ClientProfileEnabled { get; set; }
        public bool PerTenantSwitchToESTSEnabled { get; set; }
        public bool LinkPreviewEnabled { get; set; }
        public bool OutlookPayEnabled { get; set; }
        public bool ConnectorsEnabled { get; set; }
        public bool ConnectorsActionableMessagesEnabled { get; set; }
        public bool SmtpActionableMessagesEnabled { get; set; }
        public bool OfficeGraphActivitySharingOrgOptout { get; set; }
        public bool UnblockUnsafeSenderPromptEnabled { get; set; }
        public bool AsyncSendEnabled { get; set; }
        public bool RefreshSessionEnabled { get; set; }
        public bool IsAgendaMailEnabled { get; set; }
        public object NetworkThrottlingConfiguration { get; set; }
        public bool BookingsEnabled { get; set; }
        public string BookingsEnabledLastUpdateTimedatatype { get; set; }
        public DateTime BookingsEnabledLastUpdateTime { get; set; }
        public bool BookingsPaymentsEnabled { get; set; }
        public bool BookingsSocialSharingRestricted { get; set; }
        public bool BookingsAddressEntryRestricted { get; set; }
        public bool BookingsAuthEnabled { get; set; }
        public bool BookingsCreationOfCustomQuestionsRestricted { get; set; }
        public bool BookingsExposureOfStaffDetailsRestricted { get; set; }
        public bool BookingsNotesEntryRestricted { get; set; }
        public bool BookingsPhoneNumberEntryRestricted { get; set; }
        public bool BookingsMembershipApprovalRequired { get; set; }
        public bool LeanPopoutEnabled { get; set; }
        public bool OutlookMobileHelpShiftEnabled { get; set; }
        public bool OutlookMobileSingleAccountEnabled { get; set; }
        public bool OutlookMobileGCCRestrictionsEnabled { get; set; }
        public object ElevatedAccessControl { get; set; }
        public bool AuditDisabled { get; set; }
        public bool WebPushNotificationsDisabled { get; set; }
        public bool WebSuggestedRepliesDisabled { get; set; }
        public bool ConnectorsEnabledForOutlook { get; set; }
        public string ConnectorsEnabledForOutlookLastUpdateTimedatatype { get; set; }
        public DateTime ConnectorsEnabledForOutlookLastUpdateTime { get; set; }
        public bool ConnectorsEnabledForTeams { get; set; }
        public string ConnectorsEnabledForTeamsLastUpdateTimedatatype { get; set; }
        public DateTime ConnectorsEnabledForTeamsLastUpdateTime { get; set; }
        public bool ConnectorsEnabledForSharepoint { get; set; }
        public string ConnectorsEnabledForSharepointLastUpdateTimedatatype { get; set; }
        public DateTime ConnectorsEnabledForSharepointLastUpdateTime { get; set; }
        public bool ConnectorsEnabledForYammer { get; set; }
        public string ConnectorsEnabledForYammerLastUpdateTimedatatype { get; set; }
        public DateTime ConnectorsEnabledForYammerLastUpdateTime { get; set; }
        public bool AutoEnableArchiveMailbox { get; set; }
        public object OnlineMeetingsByDefaultEnabled { get; set; }
        public bool SendFromAliasEnabled { get; set; }
        public bool OutlookTextPredictionDisabled { get; set; }
        public bool MobileAppEducationEnabled { get; set; }
        public bool EnableForwardingAddressSyncForMailboxes { get; set; }
        public bool OutlookGifPickerDisabled { get; set; }
        public bool WorkspaceTenantEnabled { get; set; }
        public string BasicAuthBlockedApps { get; set; }
        public string ShortenEventScopeDefault { get; set; }
        public string DefaultMinutesToReduceShortEventsBydatatype { get; set; }
        public int DefaultMinutesToReduceShortEventsBy { get; set; }
        public string DefaultMinutesToReduceLongEventsBydatatype { get; set; }
        public int DefaultMinutesToReduceLongEventsBy { get; set; }
        public bool FindTimeAttendeeAuthenticationEnabled { get; set; }
        public bool FindTimeOnlineMeetingOptionDisabled { get; set; }
        public bool FindTimeAutoScheduleDisabled { get; set; }
        public bool FindTimeLockPollForAttendeesEnabled { get; set; }
        public bool MessageRemindersEnabled { get; set; }
        public bool IsEopTrialEnabled { get; set; }
        public bool EnableOutlookEvents { get; set; }
        public bool IsComplianceTrialEnabled { get; set; }
        public bool MessageHighlightsEnabled { get; set; }
        public bool SharedDomainEmailAddressFlowEnabled { get; set; }
        public string OrganizationConfigHash { get; set; }
        public string LegacyExchangeDN { get; set; }
        public string DisplayName { get; set; }
        public string Heuristics { get; set; }
        public string ResourceAddressListsodatatype { get; set; }
        public string[] ResourceAddressLists { get; set; }
        public bool IsMixedMode { get; set; }
        public string PreviousAdminDisplayVersion { get; set; }
        public bool IsAddressListPagingEnabled { get; set; }
        public string ForeignForestFQDNodatatype { get; set; }
        public object[] ForeignForestFQDN { get; set; }
        public object ForeignForestOrgAdminUSGSid { get; set; }
        public object ForeignForestRecipientAdminUSGSid { get; set; }
        public object ForeignForestViewOnlyAdminUSGSid { get; set; }
        public string MimeTypesodatatype { get; set; }
        public object[] MimeTypes { get; set; }
        public bool IsLicensingEnforced { get; set; }
        public bool IsTenantAccessBlocked { get; set; }
        public bool IsDualWriteEnabled { get; set; }
        public bool IsTenantInGracePeriod { get; set; }
        public bool IsDehydrated { get; set; }
        public bool IsGuidPrefixedLegacyDnDisabled { get; set; }
        public bool IsMailboxForcedReplicationDisabled { get; set; }
        public string RBACConfigurationVersion { get; set; }
        public string RootPublicFolderMailbox { get; set; }
        public string RemotePublicFolderMailboxesodatatype { get; set; }
        public object[] RemotePublicFolderMailboxes { get; set; }
        public string AdminDisplayVersion { get; set; }
        public bool IsUpgradingOrganization { get; set; }
        public bool IsUpdatingServicePlan { get; set; }
        public string ServicePlan { get; set; }
        public string TargetServicePlan { get; set; }
        public string WACDiscoveryEndpoint { get; set; }
        public string UMAvailableLanguagesodatatype { get; set; }
        public string[] UMAvailableLanguages { get; set; }
        public string AdfsAuthenticationConfiguration { get; set; }
        public object AdfsIssuer { get; set; }
        public string AdfsAudienceUrisodatatype { get; set; }
        public object[] AdfsAudienceUris { get; set; }
        public string AdfsSignCertificateThumbprintsodatatype { get; set; }
        public object[] AdfsSignCertificateThumbprints { get; set; }
        public object AdfsEncryptCertificateThumbprint { get; set; }
        public object SiteMailboxCreationURL { get; set; }
        public object DefaultDataEncryptionPolicy { get; set; }
        public bool MailboxDataEncryptionEnabled { get; set; }
        public object DefaultAuthenticationPolicy { get; set; }
        public string AllowedMailboxRegionsodatatype { get; set; }
        public string[] AllowedMailboxRegions { get; set; }
        public string DefaultMailboxRegion { get; set; }
        public object IsJitEnabled { get; set; }
        public object AutoJitForests { get; set; }
        public string DefaultMailboxRegionLastUpdateTimedatatype { get; set; }
        public DateTime DefaultMailboxRegionLastUpdateTime { get; set; }
        public string AllowedMailboxRegionsLastUpdateTimedatatype { get; set; }
        public DateTime AllowedMailboxRegionsLastUpdateTime { get; set; }
        public bool DirectReportsGroupAutoCreationEnabled { get; set; }
        public bool AllowToAddGuests { get; set; }
        public bool GuestsEnabled { get; set; }
        public bool GroupsCreationEnabled { get; set; }
        public bool HiddenMembershipGroupsCreationEnabled { get; set; }
        public string GroupsCreationWhitelistedId { get; set; }
        public string GroupsUsageGuidelinesLink { get; set; }
        public string DefaultGroupAccessType { get; set; }
        public string GroupLifeCyclePolicy { get; set; }
        public string GroupsNamingPolicy { get; set; }
        public string DataClassifications { get; set; }
        public string VisibleMeetingUpdateProperties { get; set; }
        public bool MatchSenderOrganizerProperties { get; set; }
        public bool DisableMailboxForSubstrateOnlyFinished { get; set; }
        public string InPlaceHoldsodatatype { get; set; }
        public object[] InPlaceHolds { get; set; }
        public object ServiceInstanceMove { get; set; }
        public string GuestsUsageGuidelinesLink { get; set; }
        public object OrganizationPrivacyStatementLink { get; set; }
        public bool IsMIPLabelForGroupsEnabled { get; set; }
        public bool IsGroupFoldersAndRulesEnabled { get; set; }
        public bool BlockMoveMessagesForGroupFolders { get; set; }
        public object FocusedInboxOn { get; set; }
        public string FocusedInboxOnLastUpdateTimedatatype { get; set; }
        public DateTime FocusedInboxOnLastUpdateTime { get; set; }
        public string ForestConfigVersion { get; set; }
        public string ForestConfigLastRunTimedatatype { get; set; }
        public DateTime ForestConfigLastRunTime { get; set; }
        public bool EndUserDLUpgradeFlowsDisabled { get; set; }
        public object OcmGroupId { get; set; }
        public string Id { get; set; }
        public bool IsValid { get; set; }
        public object Item { get; set; }
        public string ExchangeVersion { get; set; }
        public string DistinguishedName { get; set; }
        public string ObjectCategory { get; set; }
        public string ObjectClassodatatype { get; set; }
        public string[] ObjectClass { get; set; }
        public string WhenChangeddatatype { get; set; }
        public DateTime WhenChanged { get; set; }
        public string WhenCreateddatatype { get; set; }
        public DateTime WhenCreated { get; set; }
        public string WhenChangedUTCdatatype { get; set; }
        public DateTime WhenChangedUTC { get; set; }
        public string WhenCreatedUTCdatatype { get; set; }
        public DateTime WhenCreatedUTC { get; set; }
        public string ExchangeObjectIddatatype { get; set; }
        public string ExchangeObjectIdodatatype { get; set; }
        public string ExchangeObjectId { get; set; }
        public string OrganizationalUnitRoot { get; set; }
        public string OriginatingServer { get; set; }
    }

}
